apiVersion: apps/v1
kind: Deployment
metadata:
  name: testjenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testjenkins
  template:
    metadata:
      labels:
        app: testjenkins
    spec:
      containers:
      - name: testjenkins
        image: testjenkins:latest
        ports:
        - containerPort: 80
