apiVersion: v1
kind: Service
metadata:
  name: testjenkins-service
  namespace: prod
spec:
  type: NodePort
  selector:
    app: testjenkins
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
