apiVersion: v1
kind: Service
metadata:
  name: testjenkins-service
spec:
  type: NodePort
  selector:
    app: testjenkins
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
